import {
  Student,
  Teacher,
  Parent,
  ClassSection,
  Subject,
  AttendanceRecord,
  HomeworkAssignment,
  TimetableSlot,
  FeeInvoice,
  FinancialEntry,
  PayrollRecord,
  LeaveRequest,
  LibraryBook,
  BookCheckout,
  TransportRoute,
  HostelRoom,
  VisitorPass,
  Announcement,
  ExamSchedule,
  StudentMark,
  SystemAuditLog,
} from "../types";

export const DUMMY_STUDENTS: Student[] = [
  {
    id: "STU-1001",
    admissionNo: "ADM-2024-001",
    rollNo: "101",
    name: "Aarav Sharma",
    gender: "Male",
    dob: "2010-04-15",
    grade: "Grade 10",
    section: "A",
    parentName: "Rajesh Sharma",
    parentPhone: "+91 98765 43210",
    parentEmail: "rajesh.sharma@example.com",
    address: "42, Vasant Vihar, New Delhi",
    bloodGroup: "O+",
    admissionDate: "2021-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Paid",
    attendancePercentage: 96.5,
    hostelResident: false,
    busRoute: "Route 04 - Vasant Vihar Express",
  },
  {
    id: "STU-1002",
    admissionNo: "ADM-2024-002",
    rollNo: "102",
    name: "Ananya Verma",
    gender: "Female",
    dob: "2010-08-22",
    grade: "Grade 10",
    section: "A",
    parentName: "Sanjay Verma",
    parentPhone: "+91 98765 43211",
    parentEmail: "sanjay.v@example.com",
    address: "18, Greater Kailash II, New Delhi",
    bloodGroup: "B+",
    admissionDate: "2020-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Pending",
    attendancePercentage: 92.0,
    hostelResident: true,
  },
  {
    id: "STU-1003",
    admissionNo: "ADM-2024-003",
    rollNo: "103",
    name: "Rohan Gupta",
    gender: "Male",
    dob: "2010-01-10",
    grade: "Grade 10",
    section: "B",
    parentName: "Alok Gupta",
    parentPhone: "+91 98765 43212",
    parentEmail: "alok.gupta@example.com",
    address: "105, Saket Enclave, New Delhi",
    bloodGroup: "A+",
    admissionDate: "2019-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Paid",
    attendancePercentage: 98.2,
    hostelResident: false,
    busRoute: "Route 02 - Saket Sector 4",
  },
  {
    id: "STU-1004",
    admissionNo: "ADM-2024-004",
    rollNo: "104",
    name: "Diya Patel",
    gender: "Female",
    dob: "2011-03-30",
    grade: "Grade 9",
    section: "A",
    parentName: "Vikram Patel",
    parentPhone: "+91 98765 43213",
    parentEmail: "vikram.patel@example.com",
    address: "77, Hauz Khas Village, New Delhi",
    bloodGroup: "AB+",
    admissionDate: "2022-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Overdue",
    attendancePercentage: 88.4,
    hostelResident: false,
  },
  {
    id: "STU-1005",
    admissionNo: "ADM-2024-005",
    rollNo: "105",
    name: "Kabir Mehta",
    gender: "Male",
    dob: "2008-11-12",
    grade: "Grade 12",
    section: "Science",
    parentName: "Sunil Mehta",
    parentPhone: "+91 98765 43214",
    parentEmail: "sunil.mehta@example.com",
    address: "12, Dwarka Sector 10, New Delhi",
    bloodGroup: "O-",
    admissionDate: "2018-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Paid",
    attendancePercentage: 94.0,
    hostelResident: true,
  },
  {
    id: "STU-1006",
    admissionNo: "ADM-2024-006",
    rollNo: "106",
    name: "Sanya Roy",
    gender: "Female",
    dob: "2008-06-05",
    grade: "Grade 12",
    section: "Commerce",
    parentName: "Debashis Roy",
    parentPhone: "+91 98765 43215",
    parentEmail: "d.roy@example.com",
    address: "55, Chittaranjan Park, New Delhi",
    bloodGroup: "B+",
    admissionDate: "2018-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Partial",
    attendancePercentage: 91.5,
    hostelResident: false,
    busRoute: "Route 01 - CR Park Connector",
  },
  {
    id: "STU-1007",
    admissionNo: "ADM-2024-007",
    rollNo: "107",
    name: "Ishaan Nair",
    gender: "Male",
    dob: "2012-09-18",
    grade: "Grade 8",
    section: "A",
    parentName: "Venugopal Nair",
    parentPhone: "+91 98765 43216",
    parentEmail: "v.nair@example.com",
    address: "9, Mayur Vihar Phase 1, Delhi",
    bloodGroup: "A-",
    admissionDate: "2023-04-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    feeStatus: "Paid",
    attendancePercentage: 97.1,
    hostelResident: false,
  },
];

export const DUMMY_TEACHERS: Teacher[] = [
  {
    id: "TCH-201",
    employeeCode: "EMP-101",
    name: "Dr. Ramesh Chandra",
    email: "ramesh.chandra@school.edu",
    phone: "+91 98111 22334",
    designation: "Senior Physics Teacher & HOD",
    department: "Science",
    subjectsHandled: ["Physics", "Applied Physics"],
    primaryClassTeacherOf: "12-Science",
    qualification: "Ph.D. in Physics, M.Ed",
    joinDate: "2015-06-15",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    salary: 85000,
  },
  {
    id: "TCH-202",
    employeeCode: "EMP-102",
    name: "Sunita Deshmukh",
    email: "sunita.d@school.edu",
    phone: "+91 98111 22335",
    designation: "Mathematics Teacher",
    department: "Mathematics",
    subjectsHandled: ["Mathematics", "Statistics"],
    primaryClassTeacherOf: "10-A",
    qualification: "M.Sc. Mathematics, B.Ed",
    joinDate: "2018-04-10",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    salary: 72000,
  },
  {
    id: "TCH-203",
    employeeCode: "EMP-103",
    name: "Amitabh Banerjee",
    email: "amitabh.b@school.edu",
    phone: "+91 98111 22336",
    designation: "English Literature Faculty",
    department: "Humanities",
    subjectsHandled: ["English Literature", "Communicative English"],
    qualification: "M.A. English Literature",
    joinDate: "2020-08-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    salary: 68000,
  },
  {
    id: "TCH-204",
    employeeCode: "EMP-104",
    name: "Pooja Krishnan",
    email: "pooja.k@school.edu",
    phone: "+91 98111 22337",
    designation: "Chemistry Lecturer",
    department: "Science",
    subjectsHandled: ["Chemistry", "Organic Chemistry"],
    primaryClassTeacherOf: "10-B",
    qualification: "M.Sc. Chemistry, B.Ed",
    joinDate: "2019-07-20",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    salary: 70000,
  },
  {
    id: "TCH-205",
    employeeCode: "EMP-105",
    name: "Vikramjit Singh",
    email: "vikram.singh@school.edu",
    phone: "+91 98111 22338",
    designation: "Physical Education Director",
    department: "Sports",
    subjectsHandled: ["Physical Education", "Health Science"],
    qualification: "M.P.Ed, Sports Coaching Diploma",
    joinDate: "2016-03-01",
    status: "Active",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    salary: 65000,
  },
];

export const DUMMY_CLASSES: ClassSection[] = [
  { id: "CLS-10A", grade: "Grade 10", section: "A", classTeacherName: "Sunita Deshmukh", classTeacherId: "TCH-202", studentCount: 38, roomNo: "Room 204", capacity: 40 },
  { id: "CLS-10B", grade: "Grade 10", section: "B", classTeacherName: "Pooja Krishnan", classTeacherId: "TCH-204", studentCount: 36, roomNo: "Room 205", capacity: 40 },
  { id: "CLS-12SCI", grade: "Grade 12", section: "Science", classTeacherName: "Dr. Ramesh Chandra", classTeacherId: "TCH-201", studentCount: 42, roomNo: "Lab Annex 1", capacity: 45 },
  { id: "CLS-12COM", grade: "Grade 12", section: "Commerce", classTeacherName: "Amitabh Banerjee", classTeacherId: "TCH-203", studentCount: 35, roomNo: "Room 302", capacity: 40 },
  { id: "CLS-9A", grade: "Grade 9", section: "A", classTeacherName: "Vikramjit Singh", classTeacherId: "TCH-205", studentCount: 40, roomNo: "Room 108", capacity: 40 },
];

export const DUMMY_SUBJECTS: Subject[] = [
  { id: "SUB-101", code: "PHY-101", name: "Physics", grade: "Grade 10", type: "Core", teachersAssigned: ["Dr. Ramesh Chandra"], weeklyHours: 6 },
  { id: "SUB-102", code: "MAT-101", name: "Mathematics", grade: "Grade 10", type: "Core", teachersAssigned: ["Sunita Deshmukh"], weeklyHours: 7 },
  { id: "SUB-103", code: "ENG-101", name: "English Literature", grade: "Grade 10", type: "Core", teachersAssigned: ["Amitabh Banerjee"], weeklyHours: 5 },
  { id: "SUB-104", code: "CHE-101", name: "Chemistry", grade: "Grade 10", type: "Practical", teachersAssigned: ["Pooja Krishnan"], weeklyHours: 6 },
  { id: "SUB-105", code: "PED-101", name: "Physical Education", grade: "Grade 10", type: "Co-Curricular", teachersAssigned: ["Vikramjit Singh"], weeklyHours: 3 },
];

export const DUMMY_FEE_INVOICES: FeeInvoice[] = [
  { id: "INV-9001", invoiceNo: "INV-2026-001", studentId: "STU-1001", studentName: "Aarav Sharma", admissionNo: "ADM-2024-001", grade: "Grade 10", section: "A", term: "Term 1 (2026-27)", totalAmount: 45000, paidAmount: 45000, dueDate: "2026-07-15", paymentDate: "2026-07-10", status: "Paid", paymentMethod: "UPI" },
  { id: "INV-9002", invoiceNo: "INV-2026-002", studentId: "STU-1002", studentName: "Ananya Verma", admissionNo: "ADM-2024-002", grade: "Grade 10", section: "A", term: "Term 1 (2026-27)", totalAmount: 45000, paidAmount: 0, dueDate: "2026-07-15", status: "Pending" },
  { id: "INV-9003", invoiceNo: "INV-2026-003", studentId: "STU-1003", studentName: "Rohan Gupta", admissionNo: "ADM-2024-003", grade: "Grade 10", section: "B", term: "Term 1 (2026-27)", totalAmount: 45000, paidAmount: 45000, dueDate: "2026-07-15", paymentDate: "2026-07-12", status: "Paid", paymentMethod: "Card" },
  { id: "INV-9004", invoiceNo: "INV-2026-004", studentId: "STU-1004", studentName: "Diya Patel", admissionNo: "ADM-2024-004", grade: "Grade 9", section: "A", term: "Term 1 (2026-27)", totalAmount: 42000, paidAmount: 10000, dueDate: "2026-06-30", status: "Overdue" },
  { id: "INV-9005", invoiceNo: "INV-2026-005", studentId: "STU-1005", studentName: "Kabir Mehta", admissionNo: "ADM-2024-005", grade: "Grade 12", section: "Science", term: "Term 1 (2026-27)", totalAmount: 52000, paidAmount: 52000, dueDate: "2026-07-15", paymentDate: "2026-07-05", status: "Paid", paymentMethod: "Bank Transfer" },
];

export const DUMMY_ATTENDANCE: AttendanceRecord[] = [
  { id: "ATT-1", date: "2026-08-07", grade: "Grade 10", section: "A", studentId: "STU-1001", studentName: "Aarav Sharma", rollNo: "101", status: "Present" },
  { id: "ATT-2", date: "2026-08-07", grade: "Grade 10", section: "A", studentId: "STU-1002", studentName: "Ananya Verma", rollNo: "102", status: "Present" },
  { id: "ATT-3", date: "2026-08-07", grade: "Grade 10", section: "B", studentId: "STU-1003", studentName: "Rohan Gupta", rollNo: "103", status: "Late", remarks: "Arrived 15 mins late due to bus traffic" },
  { id: "ATT-4", date: "2026-08-07", grade: "Grade 9", section: "A", studentId: "STU-1004", studentName: "Diya Patel", rollNo: "104", status: "Absent", remarks: "Medical leave informed" },
  { id: "ATT-5", date: "2026-08-07", grade: "Grade 12", section: "Science", studentId: "STU-1005", studentName: "Kabir Mehta", rollNo: "105", status: "Present" },
];

export const DUMMY_HOMEWORK: HomeworkAssignment[] = [
  { id: "HW-501", title: "Kinematics & Newton's Laws Worksheet", subject: "Physics", grade: "Grade 10", section: "A", teacherName: "Dr. Ramesh Chandra", assignedDate: "2026-08-05", dueDate: "2026-08-10", description: "Solve numerical problems 1 to 15 from Chapter 3 textbook exercises.", totalSubmissions: 28, totalStudents: 38, attachmentName: "Physics_Worksheet_Ch3.pdf" },
  { id: "HW-502", title: "Quadratic Equations Proofs", subject: "Mathematics", grade: "Grade 10", section: "A", teacherName: "Sunita Deshmukh", assignedDate: "2026-08-06", dueDate: "2026-08-09", description: "Complete exercises 4.2 and submit clean handwritten steps.", totalSubmissions: 35, totalStudents: 38 },
  { id: "HW-503", title: "Shakespeare Essay: Julius Caesar", subject: "English Literature", grade: "Grade 12", section: "Commerce", teacherName: "Amitabh Banerjee", assignedDate: "2026-08-04", dueDate: "2026-08-12", description: "Write a 500-word critical analysis on Mark Antony's funeral speech.", totalSubmissions: 20, totalStudents: 35 },
];

export const DUMMY_TIMETABLE: TimetableSlot[] = [
  { id: "TT-1", day: "Monday", period: 1, startTime: "08:30 AM", endTime: "09:15 AM", grade: "Grade 10", section: "A", subject: "Mathematics", teacherName: "Sunita Deshmukh", roomNo: "Room 204" },
  { id: "TT-2", day: "Monday", period: 2, startTime: "09:15 AM", endTime: "10:00 AM", grade: "Grade 10", section: "A", subject: "Physics", teacherName: "Dr. Ramesh Chandra", roomNo: "Room 204" },
  { id: "TT-3", day: "Monday", period: 3, startTime: "10:15 AM", endTime: "11:00 AM", grade: "Grade 10", section: "A", subject: "Chemistry", teacherName: "Pooja Krishnan", roomNo: "Science Lab 2" },
  { id: "TT-4", day: "Monday", period: 4, startTime: "11:00 AM", endTime: "11:45 AM", grade: "Grade 10", section: "A", subject: "English Literature", teacherName: "Amitabh Banerjee", roomNo: "Room 204" },
  { id: "TT-5", day: "Tuesday", period: 1, startTime: "08:30 AM", endTime: "09:15 AM", grade: "Grade 10", section: "A", subject: "Physics", teacherName: "Dr. Ramesh Chandra", roomNo: "Room 204" },
  { id: "TT-6", day: "Tuesday", period: 2, startTime: "09:15 AM", endTime: "10:00 AM", grade: "Grade 10", section: "A", subject: "Mathematics", teacherName: "Sunita Deshmukh", roomNo: "Room 204" },
];

export const DUMMY_LIBRARY_BOOKS: LibraryBook[] = [
  { id: "BK-101", accessionNo: "LIB-9801", isbn: "978-0143452102", title: "Brief Answers to the Big Questions", author: "Stephen Hawking", category: "Science & Astronomy", publisher: "John Murray", copiesTotal: 10, copiesAvailable: 7, rackLocation: "Rack B-04" },
  { id: "BK-102", accessionNo: "LIB-9802", isbn: "978-0062316097", title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", category: "History & World", publisher: "Harper", copiesTotal: 12, copiesAvailable: 4, rackLocation: "Rack H-12" },
  { id: "BK-103", accessionNo: "LIB-9803", isbn: "978-0593078754", title: "Higher Engineering Mathematics", author: "B.S. Grewal", category: "Mathematics", publisher: "Khanna Publishers", copiesTotal: 25, copiesAvailable: 18, rackLocation: "Rack M-01" },
  { id: "BK-104", accessionNo: "LIB-9804", isbn: "978-0743273565", title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "Fiction", publisher: "Scribner", copiesTotal: 15, copiesAvailable: 11, rackLocation: "Rack F-08" },
];

export const DUMMY_BOOK_CHECKOUTS: BookCheckout[] = [
  { id: "CO-1", bookId: "BK-101", bookTitle: "Brief Answers to the Big Questions", borrowerName: "Aarav Sharma", borrowerRole: "Student", borrowerId: "STU-1001", issueDate: "2026-08-01", dueDate: "2026-08-15", status: "Issued", fineAmount: 0 },
  { id: "CO-2", bookId: "BK-102", bookTitle: "Sapiens: A Brief History of Humankind", borrowerName: "Ananya Verma", borrowerRole: "Student", borrowerId: "STU-1002", issueDate: "2026-07-20", dueDate: "2026-08-03", status: "Overdue", fineAmount: 40 },
];

export const DUMMY_TRANSPORT_ROUTES: TransportRoute[] = [
  { id: "TR-01", routeNo: "Route 01", routeName: "CR Park - Alaknanda Express", vehicleNo: "DL 01 PB 4410", driverName: "Mahesh Singh", driverPhone: "+91 97110 55432", capacity: 42, assignedStudentsCount: 38, monthlyFee: 2800, stops: ["CR Park Main Gate", "Alaknanda Market", "GK 2 M Block", "School Campus"] },
  { id: "TR-02", routeNo: "Route 02", routeName: "Saket - Malviya Nagar Loop", vehicleNo: "DL 01 PB 4412", driverName: "Suraj Kumar", driverPhone: "+91 97110 55435", capacity: 42, assignedStudentsCount: 41, monthlyFee: 3000, stops: ["Saket Metro Station", "PVR Saket", "Malviya Nagar Corner", "School Campus"] },
  { id: "TR-03", routeNo: "Route 03", routeName: "Vasant Kunj - Fortis Hub", vehicleNo: "DL 01 PB 4418", driverName: "Harpreet Singh", driverPhone: "+91 97110 55439", capacity: 35, assignedStudentsCount: 30, monthlyFee: 3200, stops: ["Vasant Kunj C Block", "Fortis Hospital Crossing", "Vasant Vihar DDA", "School Campus"] },
];

export const DUMMY_HOSTEL_ROOMS: HostelRoom[] = [
  { id: "RM-101", blockName: "Nalanda Boys Block", roomNo: "101", floor: 1, roomType: "Double", capacity: 2, occupied: 2, monthlyRent: 8500, wardenName: "Rajinder Prasad" },
  { id: "RM-102", blockName: "Nalanda Boys Block", roomNo: "102", floor: 1, roomType: "Double", capacity: 2, occupied: 1, monthlyRent: 8500, wardenName: "Rajinder Prasad" },
  { id: "RM-201", blockName: "Gargi Girls Block", roomNo: "201", floor: 2, roomType: "Double", capacity: 2, occupied: 2, monthlyRent: 8500, wardenName: "Sunita Sharma" },
  { id: "RM-202", blockName: "Gargi Girls Block", roomNo: "202", floor: 2, roomType: "Triple", capacity: 3, occupied: 2, monthlyRent: 7500, wardenName: "Sunita Sharma" },
];

export const DUMMY_VISITOR_PASSES: VisitorPass[] = [
  { id: "VIS-301", passNo: "VP-2026-089", visitorName: "Deepak Malhotra", phone: "+91 98100 77654", purpose: "Admission Enquiry for Grade 6", personToMeet: "Receptionist / Front Office", checkInTime: "10:15 AM", status: "Checked In", idProofType: "Aadhaar Card", gateNo: "Gate 1" },
  { id: "VIS-302", passNo: "VP-2026-088", visitorName: "Meenakshi Sundaram", phone: "+91 98100 77655", purpose: "Meeting Class Teacher", personToMeet: "Sunita Deshmukh", checkInTime: "09:30 AM", checkOutTime: "10:05 AM", status: "Checked Out", idProofType: "Driving License", gateNo: "Gate 1" },
];

export const DUMMY_ANNOUNCEMENTS: Announcement[] = [
  { id: "ANN-101", title: "Independence Day Cultural Celebration & Flag Hoisting", content: "All students and teachers are invited for the annual Independence Day ceremony on August 15th at 8:00 AM in the Main Auditorium. Dress code: Formal School Uniform.", publishedDate: "2026-08-06", targetAudience: "All", priority: "High", authorName: "Principal Office" },
  { id: "ANN-102", title: "First Term Examination Timetable Released", content: "The detailed schedule for Grade 9 to 12 Term 1 Examinations has been published in the Examinations tab. Students must ensure admit cards are cleared.", publishedDate: "2026-08-04", targetAudience: "Students", priority: "Urgent", authorName: "Academic Coordinator" },
  { id: "ANN-103", title: "Parent-Teacher Meeting (PTM) for Mid-Term Progress", content: "PTM will be conducted on Saturday, August 22nd from 9:00 AM to 1:00 PM. Parents can view roll-wise slots in their portal.", publishedDate: "2026-08-02", targetAudience: "Parents", priority: "Normal", authorName: "Vice Principal" },
];

export const DUMMY_EXAM_SCHEDULES: ExamSchedule[] = [
  { id: "EX-1", examName: "First Term Exam 2026", grade: "Grade 10", subject: "Mathematics", examDate: "2026-09-15", startTime: "09:00 AM", duration: "3 Hours", maxMarks: 100, passingMarks: 33, roomNo: "Exam Hall 1" },
  { id: "EX-2", examName: "First Term Exam 2026", grade: "Grade 10", subject: "Physics", examDate: "2026-09-17", startTime: "09:00 AM", duration: "3 Hours", maxMarks: 100, passingMarks: 33, roomNo: "Exam Hall 1" },
  { id: "EX-3", examName: "First Term Exam 2026", grade: "Grade 10", subject: "Chemistry", examDate: "2026-09-19", startTime: "09:00 AM", duration: "3 Hours", maxMarks: 100, passingMarks: 33, roomNo: "Exam Hall 2" },
];

export const DUMMY_STUDENT_MARKS: StudentMark[] = [
  { id: "MK-101", examName: "Unit Test 1 (2026)", studentId: "STU-1001", studentName: "Aarav Sharma", rollNo: "101", grade: "Grade 10", section: "A", subject: "Mathematics", marksObtained: 94, maxMarks: 100, gradeLetter: "A1", remarks: "Outstanding conceptual clarity" },
  { id: "MK-102", examName: "Unit Test 1 (2026)", studentId: "STU-1001", studentName: "Aarav Sharma", rollNo: "101", grade: "Grade 10", section: "A", subject: "Physics", marksObtained: 88, maxMarks: 100, gradeLetter: "A2", remarks: "Very good numerical solving" },
  { id: "MK-103", examName: "Unit Test 1 (2026)", studentId: "STU-1002", studentName: "Ananya Verma", rollNo: "102", grade: "Grade 10", section: "A", subject: "Mathematics", marksObtained: 82, maxMarks: 100, gradeLetter: "A2", remarks: "Good effort, work on geometry proofs" },
  { id: "MK-104", examName: "Unit Test 1 (2026)", studentId: "STU-1002", studentName: "Ananya Verma", rollNo: "102", grade: "Grade 10", section: "A", subject: "Physics", marksObtained: 91, maxMarks: 100, gradeLetter: "A1", remarks: "Excellent lab practical score" },
];

export const DUMMY_AUDIT_LOGS: SystemAuditLog[] = [
  { id: "LOG-901", timestamp: "2026-08-07 14:22:10", user: "Admin User", role: "Administrator", action: "Updated School Profile Settings", module: "Settings", ipAddress: "192.168.1.45" },
  { id: "LOG-902", timestamp: "2026-08-07 12:05:30", user: "Sunita Deshmukh", role: "Class Teacher", action: "Marked Attendance for Grade 10-A", module: "Attendance", ipAddress: "192.168.1.112" },
  { id: "LOG-903", timestamp: "2026-08-07 10:14:02", user: "Accountant Desk", role: "Accountant", action: "Generated Fee Receipt INV-2026-001", module: "Fees", ipAddress: "192.168.1.88" },
];
